name: Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform Plan and Apply'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v2

      - name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Initialize Terraform'
        run: terraform init -backend-config="bucket=${{ secrets.GCS_BUCKET_NAME }}" -backend-config="prefix=terraform/state"

      - name: 'Validate Terraform'
        run: terraform validate

      - name: 'Terraform Plan (Pull Request)'
        if: github.event_name == 'pull_request'
        run: |
          terraform plan \
            -var "project_id=${{ secrets.GCP_PROJECT_ID }}" \
            -var "region=${{ secrets.GCP_REGION }}" \
            -var "bucket_name=${{ secrets.GCS_BUCKET_NAME }}" \
            -lock=false

      - name: 'Terraform Plan (Push to Main)'
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          terraform plan -out=tfplan \
            -var "project_id=${{ secrets.GCP_PROJECT_ID }}" \
            -var "region=${{ secrets.GCP_REGION }}" \
            -var "bucket_name=${{ secrets.GCS_BUCKET_NAME }}"

      - name: 'Terraform Apply'
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -input=false tfplan